name: Makefile CI

inputs:
  path:
    description: "Path of the directory containing the static assets."
    required: true
    default: "build/html/"
  retention-days:
    description: "Duration after which artifact will expire in days."
    required: false
    default: "1"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4

    - name: make
      run: make html

    - name: Archive artifact
      shell: sh
      if: runner.os == 'Linux'
      run: |
        for f in $(chmod -c -R +r . | awk '{print substr($3, 2, length($3)-2)}')
        do
          echo "::warning::Added read permission to $f"
        done
        tar \
          --dereference --hard-dereference \
          --directory "$INPUT_PATH" \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .
      env:
        INPUT_PATH: ${{ inputs.path }}

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: ${{ inputs.retention-days }}
